TextPortTeams/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace TextPortTeams.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

TextPortTeams/Controllers/NumbersController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Linq;
using System.Web.Mvc;
using System.Web;
using Microsoft.Owin.Security;

using TextPort.Helpers;
using TextPortCore.Data;
using TextPortCore.Models;
using TextPortCore.Helpers;
using TextPortCore.Integrations.Bandwidth;
using TextPortCore.Integrations.Nexmo;

namespace TextPortTeams.Controllers
{
    public class NumbersController : Controller
    {
        [AllowAnonymous]
        [HttpPost]
        public ActionResult ConfirmPurchase(RegistrationData regData)
        {
            try
            {
                return PartialView("_Purchase", regData);
            }
            catch (Exception ex)
            {
                string bar = ex.Message;
                return null;
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public JsonResult GetAreaCodeName(string areaCode, bool tollFree)
        {
            using (TextPortDA da = new TextPortDA())
            {
                string description = da.GetAreaCodeName(areaCode, tollFree);
                return Json(description, JsonRequestBehavior.AllowGet);
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public JsonResult GetLeasePeriods(int countryId)
        {
            IEnumerable<SelectListItem> leasePeriods = new List<SelectListItem>();

            using (TextPortDA da = new TextPortDA())
            {
                leasePeriods = da.GetLeasePeriods(countryId);
            }
            return Json(leasePeriods, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        [HttpGet]
        public JsonResult GetAvailableNumbers(int countryId, string areaCode, bool tollFree, int count, int page)
        {
            List<SelectListItem> numbersItems = new List<SelectListItem>();

            int carrierId = 0;
            using (TextPortDA da = new TextPortDA())
            {
                Carrier carrier = da.GetCarrierForCountry(countryId);
                carrierId = carrier.CarrierId;
            }

            switch (carrierId)
            {
                case (int)Carriers.BandWidth:
                    using (Bandwidth bw = new Bandwidth())
                    {
                        List<string> numbers = bw.GetVirtualNumbersList(areaCode, count, tollFree, page);
                        if (numbers.Any())
                        {
                            if (numbers.FirstOrDefault().Equals("No more numbers"))
                            {
                                numbersItems.Add(new SelectListItem() { Text = "No more numbers", Value = string.Empty });
                                return Json(numbersItems, JsonRequestBehavior.AllowGet);
                            }

                            foreach (string number in numbers)
                            {
                                numbersItems.Add(new SelectListItem() { Text = Utilities.NumberToDisplayFormat(number, countryId), Value = number });
                            }
                        }
                        else
                        {
                            numbersItems.Add(new SelectListItem() { Text = "No available numbers", Value = string.Empty });
                        }
                    }
                    break;

                case (int)Carriers.InfoBip:
                    numbersItems.Add(new SelectListItem() { Text = Utilities.NumberToDisplayFormat("1234432345", countryId), Value = "1234432345" });
                    numbersItems.Add(new SelectListItem() { Text = Utilities.NumberToDisplayFormat("5432765434", countryId), Value = "5432765434" });
                    numbersItems.Add(new SelectListItem() { Text = Utilities.NumberToDisplayFormat("2312776309", countryId), Value = "2312776309" });
                    numbersItems.Add(new SelectListItem() { Text = Utilities.NumberToDisplayFormat("3224456832", countryId), Value = "3224456832" });
                    numbersItems.Add(new SelectListItem() { Text = Utilities.NumberToDisplayFormat("9988543232", countryId), Value = "9988543232" });
                    break;

                case (int)Carriers.Nexmo:
                    using (Nexmo nexmo = new Nexmo())
                    {
                        List<string> numbers = nexmo.GetVirtualNumbersList(countryId, count, page);
                        if (numbers.Any())
                        {
                            if (numbers.FirstOrDefault().Equals("No more numbers"))
                            {
                                numbersItems.Add(new SelectListItem() { Text = "No more numbers", Value = string.Empty });
                                return Json(numbersItems, JsonRequestBehavior.AllowGet);
                            }

                            foreach (string number in numbers)
                            {
                                numbersItems.Add(new SelectListItem() { Text = Utilities.NumberToDisplayFormat(number, countryId), Value = number });
                            }
                        }
                        else
                        {
                            numbersItems.Add(new SelectListItem() { Text = "No available numbers", Value = string.Empty });
                        }
                    }
                    break;
            }

            return Json(numbersItems, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public ActionResult Index()
        {
            bool showExpiredNumbers = Request.QueryString["exp"] != null && Request.QueryString["exp"].Equals("1");
            int accountId = Utilities.GetAccountIdFromClaim(ClaimsPrincipal.Current);

            using (TextPortDA da = new TextPortDA())
            {
                Account acc = da.GetAccountById(accountId);
                if (acc.ComplimentaryNumber == (byte)ComplimentaryNumberStatus.Eligible)
                {
                    return RedirectToAction("ComplimentaryNumber", new { id = accountId.ToString() });
                }
            }

            NumbersContainer nc = new NumbersContainer(accountId, showExpiredNumbers);
            return View(nc);
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public ActionResult GetNumber()
        {
            int accountId = Utilities.GetAccountIdFromClaim(ClaimsPrincipal.Current);
            RegistrationData regData = new RegistrationData("VirtualNumber", accountId);
            return View(regData);
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public ActionResult GetNumber(RegistrationData regData)
        {
            int accountId = Utilities.GetAccountIdFromClaim(ClaimsPrincipal.Current);

            regData.Success = false;
            regData.Status = "Failed";
            regData.CompletionTitle = "Number Assignment Failure";
            regData.CompletionMessage = $"An error occurred while attempting to assign the number {regData.VirtualNumber} to your account. Please try again. If the problem persists please contact support.";

            // Make sure the number cost is not negative. Prevents against hacks where the NumberCost field is edited to a negative value.
            if (!string.IsNullOrEmpty(regData.VirtualNumber) && accountId > 0 && regData.NumberCost >= 1)
            {
                using (TextPortDA da = new TextPortDA())
                {
                    Carrier carrier = da.GetCarrierForCountry(regData.CountryId);
                    regData.CarrierId = carrier.CarrierId;
                    bool purchaseSuccessful = false;

                    switch (regData.CarrierId)
                    {
                        case (int)Carriers.BandWidth:
                            using (Bandwidth bw = new Bandwidth())
                            {
                                purchaseSuccessful = bw.PurchaseVirtualNumber(regData);
                            }
                            break;

                        case (int)Carriers.Nexmo:
                            using (Nexmo nexmo = new Nexmo())
                            {
                                purchaseSuccessful = nexmo.PurchaseVirtualNumber(regData);
                            }
                            break;
                    }

                    if (purchaseSuccessful)
                    {
                        if (da.AddNumberToAccount(regData))
                        {
                            regData.CompletionTitle = $"{regData.NumberDisplayFormat} Successfully Assigned";
                            regData.CompletionMessage = $"The number {regData.NumberDisplayFormat} has been sucessfully assigned to your account for a period of {regData.LeasePeriod} {regData.LeasePeriodWord}.";
                            regData.Status = "Complete";
                            regData.Success = true;

                            Account acc = da.GetAccountById(regData.AccountId);
                            if (acc != null)
                            {
                                acc.Balance -= (Math.Abs(regData.NumberCost));
                                da.SaveChanges();

                                Cookies.WriteBalance(acc.Balance);
                            }
                        }
                    }
                }
            }
            return View("TransactionComplete", regData);
        }

        [Authorize(Roles = "User")]
        [HttpGet]
        public ActionResult RenewNumber(int id)
        {
            int accountId = Utilities.GetAccountIdFromClaim(ClaimsPrincipal.Current);

            RegistrationData regData = new RegistrationData("VirtualNumberRenew", accountId);

            using (TextPortDA da = new TextPortDA())
            {
                DedicatedVirtualNumber vn = da.GetVirtualNumberById(id);
                if (vn != null)
                {

TextPortTeams/Views/Numbers/ComplimentaryNumber.cshtml
@using TextPortCore.Models
@model RegistrationData

@{
    ViewBag.Title = "Complimentary / Replacement Number";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="/Scripts/TextPort/GetNumbers.js"></script>
<script src="https://www.paypalobjects.com/api/checkout.js"></script>

<div class="row">
    <div class="col-md-3 ">
        <div class="list-group ">
            <a href="/Account/Profile" class="list-group-item list-group-item-action">Profile</a>
            <a href="/Account/Balance" class="list-group-item list-group-item-action">Balance</a>
            <a href="/Numbers/" class="list-group-item list-group-item-action active">Numbers</a>
            <a href="#" class="list-group-item list-group-item-action">Contacts</a>
            <a href="#" class="list-group-item list-group-item-action">Change Password</a>
            <a href="#" class="list-group-item list-group-item-action">Delete Account</a>
        </div>
    </div>
    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                <h4>@((Model.ShowAnnouncementBanner) ? "Complimentary" : "Replacement") Number</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    @if (Model.ShowAnnouncementBanner)
                    {
                        <div class="form-group">
                            <div class="alert alert-success" role="alert">
                                <h4>Notice to Our Existing Account Holders</h4>
                                <p>
                                    All TextPort accounts now require a virtual number. The methods that allowed us to provide free texting are being phased out by mobile providers.
                                </p>
                                <p>
                                    Because of this, TextPort is offering existing account holders a <b>free number for 30 days</b>, plus credit to send approximately <b>50 free messages.</b>
                                </p>
                                <p>
                                    Use the section below to select the area code and number of your choice. You will <b>not be charged for the number</b>.
                                    Your number will automatically expire in 30 days, or you have the option to renew it.
                                </p>
                            </div>
                        </div>
                    }
                    <div class="offset-1 col-11">
                        @using (Html.BeginForm("PostPurchase", "Account", FormMethod.Post, new { id = "form-signup" }))
                        {
                            @Html.HiddenFor(m => m.NumberCost)
                            @Html.HiddenFor(m => m.AccountId)
                            @Html.HiddenFor(m => m.PurchaseType)
                            @Html.HiddenFor(m => m.PayPalCustom)
                            @Html.HiddenFor(m => m.VirtualNumberId)
                            @Html.HiddenFor(m => m.PurchaseTitle)
                            @Html.HiddenFor(m => m.ProductDescription)
                            @Html.HiddenFor(m => m.CompletionTitle)
                            @Html.HiddenFor(m => m.CompletionMessage)
                            //@Html.HiddenFor(m => m.BaseNumberCost)
                            //@Html.HiddenFor(m => m.BaseSMSCost)
                            @Html.HiddenFor(m => m.LeasePeriod)
                            <input type="hidden" id="hidTotalCost" value="0" />

                            <div class="form-group">
                                @Html.LabelFor(m => m.NumberCountryId, new { @class = "form-label" })
                                @Html.DropDownListFor(m => m.NumberCountryId, new SelectList(Model.CountriesList, "Value", "Text"), new { @class = "col-5 form-control" })
                                @Html.ValidationMessageFor(m => m.NumberCountryId, null, new { @class = "text-danger" })
                                <p class="subscript">* Number includes credit for 50 text messages.</p>
                            </div>
                            <div class="form-group" id="DivAreaCode">
                                @Html.LabelFor(m => m.AreaCode, new { @class = "form-label" })
                                <div class="row">
                                    <div class="col-2">
                                        @Html.TextBoxFor(m => m.AreaCode, new { @class = "form-control", placeholder = "000" })
                                    </div>
                                    <div id="spintiller1" class="spinner-border collapse" role="status">
                                        <span class="sr-only">Loading...</span>
                                    </div>
                                    <div class="col">
                                        <label id="AreaCodeDescription" class="col-form-label"></label>
                                    </div>
                                </div>
                                @Html.ValidationMessageFor(m => m.AreaCode, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.VirtualNumber, new { @class = "form-label" })
                                @Html.DropDownListFor(m => m.VirtualNumber, new SelectList(Model.NumbersList, "Value", "Text"), new { @class = "col-5 form-control" })
                                @Html.ValidationMessageFor(m => m.VirtualNumber, null, new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <button id="btnContinue" type="button" class="btn btn-primary">Select Number</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="purchaseModalCont" class="modal hide fade in" data-url='@Url.Action("Purchase", "Numbers")'>
</div>
<div id="postPurchaseModalCont" class="modal hide fade in">
</div>

TextPortTeams/Views/Numbers/GetNumber.cshtml
@using TextPortCore.Models
@using TextPortCore.Helpers
@model RegistrationData

@{
    ViewBag.Title = "Get Number";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src="/scripts/TextPort/GetNumbers.js"></script>
<script type="text/javascript" src="/scripts/TextPort/Purchases.js"></script>
<script type="text/javascript" src="/scripts/bootbox/bootbox.min.js"></script>

<script type="text/javascript">
    $(function () {
        $('#menu_numbers').addClass("active");

        $('#btnPurchase').click(function (e) {
            var form = $("#form-get-number");
            if (form.valid()) {

                var leasePeriodType = "";
                var leasePeriodWord = "";
                var leasePeriod = 0;
                var countryCode = $("#CountryId option:selected").val();
                var number = numberToDisplay($("#VirtualNumber").val(), countryCode);

                leasePeriodValues = $("#LeasePeriodCode").val().split("|");
                if (number !== "" && leasePeriodValues.length > 2) {
                    leasePeriodType = leasePeriodValues[0];
                    leasePeriod = parseFloat(leasePeriodValues[1]);
                    numberCost = parseFloat(leasePeriodValues[2]);

                    switch (leasePeriodType) {
                        case "D":
                            leasePeriodWord = "day";
                            break;
                        case "W":
                            leasePeriodWord = "week";
                            break;
                        case "Y":
                            leasePeriodWord = "year";
                            break;
                        default:
                            leasePeriodWord = "month";
                            break;
                    }

                    if (leasePeriod > 1) {
                        leasePeriodWord += "s";
                    }

                    bootbox.confirm({
                        title: "Get " + number + "?",
                        message: "Assign " + number + " to your account for a period of " + leasePeriod + " " + leasePeriodWord + "?<br />Your account will be debited $" + numberCost.formatMoney(),
                        buttons: {
                            cancel: {
                                label: '<i class="fa fa-times"></i> Cancel'
                            },
                            confirm: {
                                label: '<i class="fa fa-check"></i> Confirm'
                            }
                        },
                        callback: function (result) {
                            if (result) {
                                form.submit();
                            }
                        }
                    })
                }
            };
        });

        $("#lnk-change-number").on("click", function (e) {
            $("#number-chooser").toggle(500);
            $("#number-picker").toggle(500);
        });

        $("#int-number-selector").hide();
        $("#number-results").hide();
        $("#selected-number-wrap").hide();
        $("#AreaCode").mask("000");
        $("#UserName").focus();
        $('#form-get-number').validate().settings.ignore = [];
        numberCount = 35;
    });

    function getNumber(number) {
        var countryCode = $("#CountryId option:selected").val();
        $("#lbl-sel-number").text("Selected number");
        $("#lbl-sel-number").show();
        $("#selected-number").text(numberToDisplay(number, countryCode));
        $("#VirtualNumber").val(numberToE164(countryCode, number));
        $("#selected-number-wrap").show();
        $("#number-chooser").hide(500);
        $("#number-picker").hide(500);
        $("#payment-section").show(500);
        $("#form-get-number").validate().element("#VirtualNumber");
    }
</script>

<div class="row">
    @Html.Partial("_SideMenuBar")
    <div class="col-12 col-md-10">
        <div class="card">
            <div class="card-header">
                <h4>Get a new Number</h4>
            </div>
            <div class="card-body">
                <div class="offset-md-1 col-11">
                    @using (Html.BeginForm("GetNumber", "Numbers", FormMethod.Post, new { id = "form-get-number" }))
                    {
                        @Html.HiddenFor(m => m.NumberCost)
                        @Html.HiddenFor(m => m.AccountId)
                        @Html.HiddenFor(m => m.PurchaseType)
                        @Html.HiddenFor(m => m.PayPalCustom)
                        @Html.HiddenFor(m => m.VirtualNumberId)
                        @Html.HiddenFor(m => m.PurchaseTitle)
                        @Html.HiddenFor(m => m.ProductDescription)
                        @Html.HiddenFor(m => m.CompletionTitle)
                        @Html.HiddenFor(m => m.CompletionMessage)
                        @Html.HiddenFor(m => m.LeasePeriodType)
                        @Html.HiddenFor(m => m.LeasePeriod)
                        @Html.HiddenFor(m => m.Success)
                        @Html.HiddenFor(m => m.Status)
                        @Html.HiddenFor(m => m.VirtualNumber)
                        <input type="hidden" id="hidTotalCost" value="0" />

                        <div class="form-group">
                            @Html.LabelFor(m => m.CountryId, new { @class = "form-label" })
                            <select name="CountryId" id="CountryId" class="form-control" data-val="true" data-val-required="A country is required">
                                @foreach (Country c in Model.CountriesList)
                                {
                                    <option value="@c.CountryId">@($"{c.CountryName}  (+{c.CountryPhoneCode})")</option>
                                }
                            </select>
                            @Html.ValidationMessageFor(m => m.CountryId, null, new { @class = "text-danger" })
                        </div>
                        <div class="form-group mb-0">
                            <label id="lbl-sel-number" class="form-label pb-1">Search by area code</label>
                            <div id="selected-number-wrap">
                                <label id="selected-number" class="vn-sel-num">@Model.NumberDisplayFormat</label>
                                <a id="lnk-change-number" href="#">change</a>
                            </div>
                        </div>
                        <div id="number-chooser">
                            <input type="text" id="area-code" class="form-control ac-input mb-2" , placeholder="Area Code" />
                            @Html.Partial("_NumberPicker")
                        </div>
                        @Html.ValidationMessageFor(m => m.VirtualNumber, null, new { @class = "text-danger" })
                        <div class="form-group pt-3">
                            @Html.LabelFor(m => m.LeasePeriodCode, new { @class = "form-label" })
                            @Html.DropDownListFor(m => m.LeasePeriodCode, new SelectList(Model.LeasePeriodsList, "Value", "Text"), new { @class = "col-md-5 form-control" })
                            @Html.ValidationMessageFor(m => m.LeasePeriodCode, null, new { @class = "text-danger" })
                        </div>
                        <div class="row lower-label">
                            <label>Available Credit</label>
                            <label id="AvailableCredit">@Formatting.DisplayMoney(Model.CreditCurrentBalance)</label>
                        </div>
                        <div class="row lower-label">
                            <label>Remaining Credit After Purchase</label>
                            <label id="RemainingCredit"></label>
                        </div>
                        <div id="creditOK">
                            <div class="form-group">
                                <button id="btnPurchase" type="button" class="btn btn-primary">@(Model.PurchaseType == "ComplimentaryNumber" ? "Select Number" : "Complete Purchase")</button>
                            </div>
                        </div>
                        <div id="creditInsufficient" style="display: none">
                            <div class="pl-0">
                                <p class="alert alert-danger text-center">
                                    Your balance is not sufficient to make this purchase.
                                    <br />
                                    <br />
                                    <a href="/account/balance" class="btn btn-danger" role="button" aria-disabled="true">Top Up Credit</a>
                                </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

TextPortTeams/Views/Numbers/Manage.cshtml
@using TextPortCore.Models
@model NumbersContainer
@{
    ViewBag.Title = "Manage Numbers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="~/content/css/messaging.css">

<script type="text/javascript">
    $(function () {
        $('#cbShowAll').on("click", function (e) {
            if ($(this).is(":checked")) {
                window.location.href = "/numbers/manage?exp=1";
            }
            else if ($(this).is(":not(:checked)")) {
                window.location.href = "/numbers/manage";
            }
        });

        $('#menu_numbers').addClass("active");
    });

    //function showHistory(virtualNumberId) {
    //    showModal("historyModalCont", "/numbers/numberhistory/" + virtualNumberId);
    //}
</script>

<div class="row">
    @Html.Partial("_SideMenuBar")
    <div class="col-12 col-md-9">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-6">
                        <h4>My Numbers</h4>
                    </div>
                    <div class="col-6 text-right">
                        @Html.ActionLink("Get a Number", "GetNumber", "Numbers", null, htmlAttributes: new { @class = "btn btn-success" })
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <td colspan="6">
                                <input id="cbShowAll" type="checkbox" checked="@Model.ShowExpiredNumbers" />
                                <label>Show expired numbers</label>
                            </td>
                        </tr>
                        <tr class="bg-primary">
                            <th scope="col" class="text-white">Number</th>
                            <th scope="col" class="text-white">Country</th>
                            <th scope="col" class="text-white">Purchased</th>
                            <th scope="col" class="text-white">Expires</th>
                            <th scope="col" class="text-white">Active</th>
                            <th scope="col" class="text-white">Renew</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ int rowId = 1; }
                        @foreach (DedicatedVirtualNumber vn in Model.Numbers)
                        {
                            string bgClass;
                            if (rowId % 2 == 0)
                            {
                                bgClass = "table-primary";
                            }
                            else
                            {
                                bgClass = string.Empty;
                            }
                            rowId++;
                            <tr class="@bgClass">
                                <td><a href="#" class="modal-button" data-toggle="modal" data-target="#modal-cont" data-url="/numbers/numberhistory/@vn.VirtualNumberId">@vn.NumberDisplayFormat</a></td>
                                <td>US</td>
                                <td>@String.Format("{0:yyyy-MM-dd}", vn.CreateDate)</td>
                                <td>@String.Format("{0:yyyy-MM-dd}", vn.ExpirationDate)</td>
                                <td>@(vn.Cancelled ? "No" : "Yes")</td>
                                <td>@Html.ActionLink("Renew", "RenewNumber", "Numbers", new { id = vn.VirtualNumberId }, htmlAttributes: new { @class = "" })</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>